from typing import Any

class ZDXAgentMemory:
    agent_id: str
    spatial: bool
    def __init__(self, agent_id: str = ..., base_dir: str = ..., *, spatial: bool = ..., spatial_width: int = ..., spatial_height: int = ..., spatial_execution_rows: int = ..., spatial_path: str | None = ..., spatial_layout: Any = ..., spatial_region: str | None = ...) -> None: ...
    @property
    def is_spatial(self) -> bool: ...
    @property
    def capacity_bytes(self) -> int | None: ...
    @property
    def frame_path(self) -> str | None: ...
    @property
    def layout(self) -> Any: ...
    @property
    def region(self) -> Any: ...
    def spatial_transaction(self, mutator: Any) -> Any: ...
    def remember(self, key: str, value: Any) -> str: ...
    def recall(self, key: str, default: Any = ...) -> Any: ...
    def forget(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def keys(self) -> list: ...
    def snapshot(self) -> dict: ...
    def update(self, data: dict) -> None: ...
    def clear(self) -> None: ...
    def append(self, key: str, item: Any) -> None: ...
    def recall_list(self, key: str) -> list: ...
    def generation(self) -> int | None: ...
