from typing import Any
from zdx_spatial_frame import SpatialFrame, SpatialLayout

class SpatialPixelStore:
    path: str
    layout: SpatialLayout
    region: str | None
    def __init__(self, path: str = ..., *, layout: SpatialLayout | None = ..., width: int = ..., height: int = ..., execution_rows: int = ..., region: str | None = ..., lock_timeout: float = ...) -> None: ...
    @property
    def capacity_bytes(self) -> int: ...
    @property
    def frame_path(self) -> str: ...
    def encoded_document_size(self, values: dict) -> int: ...
    def load_resident_snapshot(self) -> tuple[SpatialFrame, dict, int, str]: ...
    def commit_snapshot(self, frame: SpatialFrame, values: dict, *, vm_generation: int, vm_checkpoint_hash: str, expected_artifact_sha256: str | None = ...) -> dict: ...
    def transaction_frame(self, mutator: Any) -> Any: ...
    def write(self, key: str, value: Any) -> str: ...
    def update(self, data: Any) -> str: ...
    def read(self, key: str, default: Any = ...) -> Any: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def keys(self) -> list: ...
    def all(self) -> dict: ...
    def clear(self) -> None: ...
    def generation(self) -> int: ...
